//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace frutas.Admin
{
    public partial class Logs
    {
        protected global::System.Web.UI.WebControls.DropDownList ddlSeveridad;
        protected global::System.Web.UI.WebControls.DropDownList ddlAccion;
        protected global::System.Web.UI.WebControls.TextBox txtUsuario;
        protected global::System.Web.UI.WebControls.TextBox txtFechaDesde;
        protected global::System.Web.UI.WebControls.TextBox txtFechaHasta;
        protected global::System.Web.UI.WebControls.Button btnBuscar;
        protected global::System.Web.UI.WebControls.Button btnLimpiar;
        protected global::System.Web.UI.WebControls.Label lblTotalLogs;
        protected global::System.Web.UI.WebControls.Label lblLogsExitosos;
        protected global::System.Web.UI.WebControls.Label lblLogsAdvertencia;
        protected global::System.Web.UI.WebControls.Label lblLogsError;
        protected global::System.Web.UI.WebControls.Label lblPaginaActual;
        protected global::System.Web.UI.WebControls.Label lblTotalPaginas;
        protected global::System.Web.UI.WebControls.Label lblTotalRegistros;
        protected global::System.Web.UI.WebControls.GridView gvLogs;
        protected global::System.Web.UI.WebControls.DropDownList ddlTamañoPagina;
        protected global::System.Web.UI.WebControls.Button btnPrimera;
        protected global::System.Web.UI.WebControls.Button btnAnterior;
        protected global::System.Web.UI.WebControls.TextBox txtPagina;
        protected global::System.Web.UI.WebControls.Label lblTotalPaginasFooter;
        protected global::System.Web.UI.WebControls.Button btnSiguiente;
        protected global::System.Web.UI.WebControls.Button btnUltima;
    }
}